### ISSUE TITLE
Facing direction is locked if player attack at the same time as they receive damage

### ISSUE THREAD

**Issue by nvatuan** [lamnguyenkhoa/SilkMelody#3]
* **Build**: BatterDemo 2022/01/08

* **Problem:** If you time your attack right at the moment you receive damage, the player facing direction is locked until they receive damage again.

* **Screencap:**

https://user-images.githubusercontent.com/24392632/148671016-090a9308-d3f2-4367-8017-bc6ec36b14f7.mp4

**Comment by lamnguyenkhoa** [comment]
Fixed
